# -*- mode: ruby -*-
# vi: set ft = ruby :

Vagrant.configure('2') do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  config.vm.box = 'bento/ubuntu-16.04-i386'
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000
end